#!/bin/sh

[ "$(pidof -x $(basename $0) -o %PPID)" ] && echo "already running" && exit

# Location of the virtual mic
DEFAULT_MIC=alsa_input.usb-GeneralPlus_USB_Audio_Device-00.mono-fallback
VIRTUAL_MIC="${XDG_HOME_DIR:-$HOME}/.local/share/bashpad/virtualmic"
SOUNDS="${XDG_HOME_DIR:-$HOME}/.local/share/bashpad/sounds"

rm "$VIRTUAL_MIC"

FILE="$(ls "$SOUNDS" | grep "^$1-")"

[ -z $(pgrep bashpad) ] && echo Already running! && exit 0

pipeid=$(pactl load-module module-pipe-source source_name=bashpad file="$VIRTUAL_MIC" format=s16le rate=16000 channels=1)
loopid=$(pactl load-module module-loopback source=bashpad)

# Set the virtual source as default, 
#  play the sound and come back to the default source
pactl set-default-source bashpad
ffmpeg -y -re -i "$SOUNDS/$FILE" -f s16le -ar 16000 -ac 1 "$VIRTUAL_MIC"
pactl set-default-source "$DEFAULT_MIC"

echo Unloading pipe module: $pipeid
pactl unload-module $pipeid
echo Unloading loopback module: $loopid
pactl unload-module $loopid

exit
